networks:
  default:
    driver: bridge

services:
  explorer:
    container_name: dilithium-rpc-explorer
    #define $UID, $GID in .env file the user to run docker and write in data folder
    #user: "1000:1000"
    environment:
      DILITHIUMEXP_HOST: 0.0.0.0
      DILITHIUMEXP_BITCOIND_URI: $DILITHIUMEXP_BITCOIND_URI
      DILITHIUMEXP_ADDRESS_API: $DILITHIUMEXP_ADDRESS_API
      DILITHIUMEXP_ELECTRUM_SERVERS: $DILITHIUMEXP_ELECTRUM_SERVERS
      DILITHIUMEXP_SLOW_DEVICE_MODE: false
      #More information mode, including Dilithium exchange rates
      #More privacy mode, no external queries
      # DILITHIUMEXP_PRIVACY_MODE: true
      # DILITHIUMEXP_NO_RATES: true
      # DILITHIUMEXP_UI_THEME: dark
    build:
      context: ./
    image: dilithium-rpc-explorer:latest
    #restart: "no"
    ports:
      - "3002:3002"
